### ISSUE TITLE
tests message prints whole path instead of just filename

### ISSUE THREAD

**Issue by greg-is-kub** [rdentato/tst#2]
This comes from the use of __FILE__ macro [here](https://github.com/rdentato/tst/blob/f682669e7fe52bb0518c14d2710582e4cf8f42d1/src/tst.h#L84) and [there](https://github.com/rdentato/tst/blob/f682669e7fe52bb0518c14d2710582e4cf8f42d1/src/tst.h#L97) 

Suggestion : add __FILENAME__ macro found [here](https://stackoverflow.com/questions/31050113/how-to-extract-the-source-filename-without-path-and-suffix-at-compile-time) and replace every call of `__FILE__` with  `__FILENAME__`

```
#define __FILENAME__ (__builtin_strrchr(__FILE__, '/') ? __builtin_strrchr(__FILE__, '/') + 1 : __FILE__)
```

however `__FILENAME__` isn't a string litteral. Hence the 2nd call must be replaced like so : 
```
    for( int tst = !( fputs( "FILE ▷ ", stderr ), fputs( __FILENAME__, stderr ), fprintf( stderr, " " __VA_ARGS__ ), fputc( '\n', stderr ), tst_init_run() ); \
```

**Comment by rdentato** [comment]
@greg-is-kub. Thanks for the suggestion!
I wonder, however, if this could not cause a problem for projects that might have the same file name under different directories.
Yes, they shouldn't :)
But what if they do? 
So I switched the printing of the full path off but the user can turn it on again by compiling with `TSTFULLPATH` defined. I've also updated the README file.
It's great to have feedback like this.

**Comment by rdentato** [comment]
ANd thanks to you pointing me to to `check2` I was wondering if I should simplify  and make `testrun()` take the role of `main`.

Let's do it. But please let me know what you think.

**Comment by rdentato** [comment]
A thought: wouldn't it be better to add the full `__FILE__` name at the beginning and remove it from the single lines leaving only the line number?

**Comment by greg-is-kub** [comment]
Thats a good idea ! This would remove the need fore the `__FILENAME__` macro & give a more minimal display.
Imo having  "test / fail message / file / line is a bit cluttery.

**Comment by rdentato** [comment]
You can have a look at the `devel` branch. 
Another functionality could be to produce a compact machine-friendly log that would be expanded into a fullyu human-readable log by another script. What do you think?

**Comment by rdentato** [comment]
CLosing.
Full path only at the top of the run. Only the line number is reported for each test.
