### ISSUE TITLE
Adding colors to to highlight test pass / fail

### ISSUE THREAD

**Issue by greg-is-kub** [rdentato/tst#4]
Hi again ! 
You asked me to do some feature requests so here is a 1st one : 

I can't show you the output because of NDA stuff sorry.

The feature request is using ANSI escape codes to add colors, this would help highlight  running a lot of tests simultaneously it is hard to find which test passed and which one has failed.
Using ansi escape codes for colors would help a lot to retrieve this information at 1st glance.
```
Purple='\033[0;35m' # Purple
Blue='\033[0;34m'   # Blue
Red='\033[0;31m'    # Red
Cyan='\033[0;36m'   # Cyan
NC='\033[0m'        # No Color
# Bold
BGreen='\033[1;32m'  # Green
BRed='\033[1;31m'    # Red
BYellow='\033[1;33m' # Yellow
BBlue='\033[1;34m'   # Blue
# High intensity
IGreen='\033[0;92m'  #Green
IBlue='\033[0;94m'   #Blue
IPurple='\033[0;95m' #Purple
ICyan='\033[0;96m'   #Cyan
```

**Comment by rdentato** [comment]
Thanks. 
I've categorized it as a feature request.

I'm really thinking about haveing the functions producing a minimal output and write a filter to convert it to a more readable format (or to XML, or using TAP syntax, and so on). 

Let's see when I'll start working seriously on it.

**Comment by greg-is-kub** [comment]
Well I've just discovered about TAP, I love the pretty formatting it offers. But it seems that most TAP outputs seems to be formatted by javascript. Wouldn't this add a lot of dependencies & complexity? This framework here is a minimal test framework for C/C++. Its appeal is its simplicty and absence of dependency with main users being ppl doing embedded / low level programming.

As for XML, would this add the need for an xml writer (+ browser for opening)? 

All in all my question is : is this level of complexity necessary when you can have a pretty colorful output on the terminal?

But as I said I've just discovered about TAP so of course if you have an idea for simple implementation feel free to go \o

**Comment by rdentato** [comment]
I've just added colors (green for pass and red for fail) in the devel branch.
They are enabled by default but you can compile with "TST_STR_NOCOLOR" defined to remove them.
TNS_STR_COMPACT implies TNS_STR_NOCOLOR:

**Comment by rdentato** [comment]
@greg-is-kub, would you add more colors, or just green/red are enough?

**Comment by rdentato** [comment]
Closing. RED/GREEN/YELLOW used to highlight FAIL/PASS/SKIP.

**Comment by rdentato** [comment]
Closing. RED/GREEN/YELLOW used to highlight FAIL/PASS/SKIP.
